name: Deploy Pre-Published ASP.NET Files to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Zip pre-published output
        run: Compress-Archive -Path bin\Release\publish\* -DestinationPath publish.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TASWebApp'
          slot-name: 'Production'
          package: publish.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4F0EB2BB411740919E8C01B334C556B2 }}
